export type FruitOption = {
  id: number;
  name: string;
  isStatus: boolean;
};

export const FRUIT_OPTIONS: FruitOption[] = [
  { id: 1, name: "同族加撃", isStatus: true },
  { id: 2, name: "同族加撃速", isStatus: true },
  { id: 3, name: "同族加命撃", isStatus: true },
  { id: 4, name: "撃種加撃", isStatus: true },
  { id: 5, name: "撃種加撃速", isStatus: true },
  { id: 6, name: "撃種加命撃", isStatus: true },
  { id: 7, name: "戦型加撃", isStatus: true },
  { id: 8, name: "戦型加撃速", isStatus: true },
  { id: 9, name: "戦型加命撃", isStatus: true },
  { id: 10, name: "同族加命", isStatus: true },
  { id: 11, name: "同族加速", isStatus: true },
  { id: 12, name: "同族加速命", isStatus: true },
  { id: 13, name: "撃種加命", isStatus: true },
  { id: 14, name: "撃種加速", isStatus: true },
  { id: 15, name: "撃種加速命", isStatus: true },
  { id: 16, name: "戦型加命", isStatus: true },
  { id: 17, name: "戦型加速", isStatus: true },
  { id: 18, name: "戦型加速命", isStatus: true },
  { id: 19, name: "友撃", isStatus: false },
  { id: 20, name: "ケガ減り", isStatus: false },
  { id: 21, name: "将命削り", isStatus: false },
  { id: 22, name: "兵命削り", isStatus: false },
  { id: 23, name: "一撃失心", isStatus: false },
  { id: 24, name: "速必殺", isStatus: false },
  { id: 25, name: "毒がまん", isStatus: false },
  { id: 26, name: "ちび癒し", isStatus: false },
  { id: 27, name: "ハート強化", isStatus: false },
  { id: 28, name: "学び", isStatus: false },
  { id: 29, name: "荒稼ぎ", isStatus: false },
  { id: 30, name: "スピクリ", isStatus: false },
  { id: 31, name: "Sランク", isStatus: false },
  { id: 32, name: "スコア稼ぎ", isStatus: false },
];

export const CREST_OPTIONS = [
  "対火の心得",
  "対水の心得",
  "対木の心得",
  "対光の心得",
  "対闇の心得",
  "対弱の心得",
  "対将の心得",
  "対兵の心得",
  "守護獣の加勢",
  "不屈の防御",
  "不屈の闘力",
  "不屈の速度",
  "不屈の必殺",
  "収監回避",
  "鎖縛回避",
  "HWマスター",
  "ハートパネルマスター",
  "伝染抵抗",
  "ゲージ必中",
  "精神力",
  "NP耐性",
  "火柱耐性",
  "窮地の活路",
  "常冷却",
  "変身回復",
  "運技の発揮",
] as const;
