import type { FruitGrade } from "@/lib/teamcustom/types";

export type FruitOption = {
  id: number;
  name: string;
  isStatus: boolean;
  bonuses: Record<FruitGrade, { hp: number; attack: number; speed: number }>;
};

const EMPTY_BONUS = { hp: 0, attack: 0, speed: 0 };

export const FRUIT_OPTIONS: FruitOption[] = [
  { id: 1, name: "同族加撃", isStatus: true, bonuses: { L: { hp: 0, attack: 3000, speed: 0 }, EL: { hp: 0, attack: 3300, speed: 0 } } },
  { id: 2, name: "同族加撃速", isStatus: true, bonuses: { L: { hp: 0, attack: 2000, speed: 26.6 }, EL: { hp: 0, attack: 2200, speed: 29.3 } } },
  { id: 3, name: "同族加命撃", isStatus: true, bonuses: { L: { hp: 2000, attack: 2000, speed: 0 }, EL: { hp: 2200, attack: 2200, speed: 0 } } },
  { id: 4, name: "撃種加撃", isStatus: true, bonuses: { L: { hp: 0, attack: 1500, speed: 0 }, EL: { hp: 0, attack: 1650, speed: 0 } } },
  { id: 5, name: "撃種加撃速", isStatus: true, bonuses: { L: { hp: 0, attack: 1000, speed: 13.2 }, EL: { hp: 0, attack: 1100, speed: 14.5 } } },
  { id: 6, name: "撃種加命撃", isStatus: true, bonuses: { L: { hp: 1000, attack: 1000, speed: 0 }, EL: { hp: 1100, attack: 1100, speed: 0 } } },
  { id: 7, name: "戦型加撃", isStatus: true, bonuses: { L: { hp: 0, attack: 1500, speed: 0 }, EL: { hp: 0, attack: 1650, speed: 0 } } },
  { id: 8, name: "戦型加撃速", isStatus: true, bonuses: { L: { hp: 0, attack: 1000, speed: 13.2 }, EL: { hp: 0, attack: 1100, speed: 14.5 } } },
  { id: 9, name: "戦型加命撃", isStatus: true, bonuses: { L: { hp: 1000, attack: 1000, speed: 0 }, EL: { hp: 1100, attack: 1100, speed: 0 } } },
  { id: 10, name: "同族加命", isStatus: true, bonuses: { L: { hp: 2500, attack: 0, speed: 0 }, EL: { hp: 2750, attack: 0, speed: 0 } } },
  { id: 11, name: "同族加速", isStatus: true, bonuses: { L: { hp: 0, attack: 0, speed: 33.3 }, EL: { hp: 0, attack: 0, speed: 36.6 } } },
  { id: 12, name: "同族加速命", isStatus: true, bonuses: { L: { hp: 2000, attack: 0, speed: 26.6 }, EL: { hp: 2200, attack: 0, speed: 29.3 } } },
  { id: 13, name: "撃種加命", isStatus: true, bonuses: { L: { hp: 1250, attack: 0, speed: 0 }, EL: { hp: 1375, attack: 0, speed: 0 } } },
  { id: 14, name: "撃種加速", isStatus: true, bonuses: { L: { hp: 0, attack: 0, speed: 16.6 }, EL: { hp: 0, attack: 0, speed: 18.3 } } },
  { id: 15, name: "撃種加速命", isStatus: true, bonuses: { L: { hp: 0, attack: 0, speed: 13.2 }, EL: { hp: 0, attack: 0, speed: 14.5 } } },
  { id: 16, name: "戦型加命", isStatus: true, bonuses: { L: { hp: 1250, attack: 0, speed: 0 }, EL: { hp: 1375, attack: 0, speed: 0 } } },
  { id: 17, name: "戦型加速", isStatus: true, bonuses: { L: { hp: 0, attack: 0, speed: 16.6 }, EL: { hp: 0, attack: 0, speed: 18.3 } } },
  { id: 18, name: "戦型加速命", isStatus: true, bonuses: { L: { hp: 0, attack: 0, speed: 13.2 }, EL: { hp: 0, attack: 0, speed: 14.5 } } },
  { id: 33, name: "孤高加撃", isStatus: true, bonuses: { L: { hp: 0, attack: 3000, speed: 0 }, EL: { hp: 0, attack: 3300, speed: 0 } } },
  { id: 19, name: "友撃", isStatus: false, bonuses: { L: EMPTY_BONUS, EL: EMPTY_BONUS } },
  { id: 20, name: "ケガ減り", isStatus: false, bonuses: { L: EMPTY_BONUS, EL: EMPTY_BONUS } },
  { id: 21, name: "将命削り", isStatus: false, bonuses: { L: EMPTY_BONUS, EL: EMPTY_BONUS } },
  { id: 22, name: "兵命削り", isStatus: false, bonuses: { L: EMPTY_BONUS, EL: EMPTY_BONUS } },
  { id: 23, name: "一撃失心", isStatus: false, bonuses: { L: EMPTY_BONUS, EL: EMPTY_BONUS } },
  { id: 24, name: "速必殺", isStatus: false, bonuses: { L: EMPTY_BONUS, EL: EMPTY_BONUS } },
  { id: 25, name: "毒がまん", isStatus: false, bonuses: { L: EMPTY_BONUS, EL: EMPTY_BONUS } },
  { id: 26, name: "ちび癒し", isStatus: false, bonuses: { L: EMPTY_BONUS, EL: EMPTY_BONUS } },
  { id: 27, name: "ハート強化", isStatus: false, bonuses: { L: EMPTY_BONUS, EL: EMPTY_BONUS } },
  { id: 28, name: "学び", isStatus: false, bonuses: { L: EMPTY_BONUS, EL: EMPTY_BONUS } },
  { id: 29, name: "荒稼ぎ", isStatus: false, bonuses: { L: EMPTY_BONUS, EL: EMPTY_BONUS } },
  { id: 30, name: "スピクリ", isStatus: false, bonuses: { L: EMPTY_BONUS, EL: EMPTY_BONUS } },
  { id: 31, name: "Sランク", isStatus: false, bonuses: { L: EMPTY_BONUS, EL: EMPTY_BONUS } },
  { id: 32, name: "スコア稼ぎ", isStatus: false, bonuses: { L: EMPTY_BONUS, EL: EMPTY_BONUS } },
];

export const CREST_OPTIONS = [
  "対火の心得",
  "対水の心得",
  "対木の心得",
  "対光の心得",
  "対闇の心得",
  "対弱の心得",
  "対将の心得",
  "対兵の心得",
  "守護獣の加勢",
  "不屈の防御",
  "不屈の闘力",
  "不屈の速度",
  "不屈の必殺",
  "収監回避",
  "鎖縛回避",
  "HWマスター",
  "ハートパネルマスター",
  "伝染抵抗",
  "ゲージ必中",
  "精神力",
  "NP耐性",
  "火柱耐性",
  "窮地の活路",
  "常冷却",
  "変身回復",
  "運技の発揮",
] as const;

export const CREST_ID_BY_NAME: Record<(typeof CREST_OPTIONS)[number], number> = {
  対火の心得: 1,
  対水の心得: 2,
  対木の心得: 3,
  対光の心得: 4,
  対闇の心得: 5,
  対弱の心得: 6,
  対将の心得: 7,
  対兵の心得: 8,
  守護獣の加勢: 9,
  不屈の防御: 10,
  不屈の闘力: 11,
  不屈の速度: 12,
  不屈の必殺: 13,
  収監回避: 14,
  鎖縛回避: 15,
  HWマスター: 16,
  ハートパネルマスター: 17,
  伝染抵抗: 18,
  ゲージ必中: 19,
  精神力: 20,
  NP耐性: 21,
  火柱耐性: 22,
  窮地の活路: 23,
  常冷却: 24,
  変身回復: 25,
  運技の発揮: 26,
};

export const CREST_GRADE_LABEL: Record<0 | 1 | 2, string> = {
  0: "",
  1: "・上",
  2: "・極",
};

export const CREST_AVAILABLE_GRADES_BY_ID: Record<number, Array<0 | 1 | 2>> = {
  1: [0, 1, 2],
  2: [0, 1, 2],
  3: [0, 1, 2],
  4: [0, 1, 2],
  5: [0, 1, 2],
  6: [0, 1, 2],
  7: [0, 1, 2],
  8: [0, 1, 2],
  9: [0, 1, 2],
  10: [0],
  11: [0],
  12: [0],
  13: [0],
  14: [0],
  15: [0],
  16: [0, 1, 2],
  17: [0, 1, 2],
  18: [0, 1],
  19: [0],
  20: [0, 1, 2],
  21: [0, 2],
  22: [0, 2],
  23: [0, 1, 2],
  24: [0],
  25: [0, 1, 2],
  26: [0, 1, 2],
};
